-- Drop tables if they exist to ensure a clean migration, including dependent objects.
DROP TABLE IF EXISTS public.user_answers CASCADE;
DROP TABLE IF EXISTS public.test_sessions CASCADE;

-- 1. Create test_sessions table
CREATE TABLE public.test_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    unit_id BIGINT REFERENCES public.units(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    completed_at TIMESTAMPTZ,
    settings JSONB
);

COMMENT ON TABLE public.test_sessions IS 'Represents a single test attempt by a user for a unit.';
COMMENT ON COLUMN public.test_sessions.settings IS 'Stores test settings like question count, time limit, etc.';

-- Indexes for performance
CREATE INDEX idx_test_sessions_user_id ON public.test_sessions(user_id);
CREATE INDEX idx_test_sessions_unit_id ON public.test_sessions(unit_id);


-- 2. Create user_answers table
CREATE TABLE public.user_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES public.test_sessions(id) ON DELETE CASCADE NOT NULL,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    selected_option_id BIGINT, -- REFERENCES public.question_options(id) temporarily removed
    answer_text TEXT,
    is_correct BOOLEAN NOT NULL,
    answered_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    duration_seconds INTEGER
);

COMMENT ON TABLE public.user_answers IS 'Stores a user''s answer to a specific question within a test session.';
COMMENT ON COLUMN public.user_answers.duration_seconds IS 'Time taken to answer the question, in seconds.';

-- Indexes for performance
CREATE INDEX idx_user_answers_session_id ON public.user_answers(session_id);
CREATE INDEX idx_user_answers_question_id ON public.user_answers(question_id);
CREATE INDEX idx_user_answers_user_id_is_correct ON public.user_answers(user_id, is_correct);


-- 3. Enable RLS for the new tables
ALTER TABLE public.test_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_answers ENABLE ROW LEVEL SECURITY;


-- 4. RLS Policies for test_sessions table

-- Users can see their own test sessions
CREATE POLICY "Allow users to read their own test sessions"
ON public.test_sessions
FOR SELECT
USING (auth.uid() = user_id);

-- Users can create their own test sessions
CREATE POLICY "Allow users to create their own test sessions"
ON public.test_sessions
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Users can update their own test sessions (e.g., to set completed_at)
CREATE POLICY "Allow users to update their own test sessions"
ON public.test_sessions
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Optional: Allow users to delete their own sessions.
CREATE POLICY "Allow users to delete their own test sessions"
ON public.test_sessions
FOR DELETE
USING (auth.uid() = user_id);


-- 5. RLS Policies for user_answers table

-- Users can see their own answers
CREATE POLICY "Allow users to read their own answers"
ON public.user_answers
FOR SELECT
USING (auth.uid() = user_id);

-- Users can insert their own answers
CREATE POLICY "Allow users to insert their own answers"
ON public.user_answers
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- NOTE: UPDATE and DELETE policies for user_answers are intentionally omitted.
-- An answer, once submitted, should generally be immutable from the client-side
-- to maintain data integrity for statistics.
